/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paryle;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.awt.*;
/**
 *
 * @author adi
 */
public class DashboardCustomer extends javax.swing.JFrame {

    private final double SINGLE_ROOM_PRICE = 100000;
    private final double DOUBLE_ROOM_PRICE = 150000;
    private final double SUITE_ROOM_PRICE = 300000;
    private final double DELUXE_ROOM_PRICE = 250000;
    /**
     * Creates new form DashboradCustomer
     */
    public DashboardCustomer() {
        initComponents();
        
        if (jComboBoxTipeKamar != null && jComboBoxTipeKamar.getItemCount() == 0) {
            jComboBoxTipeKamar.addItem("pilih"); // Default placeholder
            jComboBoxTipeKamar.addItem("Single Room");
            jComboBoxTipeKamar.addItem("Double Room");
            jComboBoxTipeKamar.addItem("Suite Room");
            jComboBoxTipeKamar.addItem("Deluxe Room");
        }
        clearFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNama = new javax.swing.JTextField();
        jTextFieldNIK = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldLamaMenginap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTotalHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUangBayar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldUangKembali = new javax.swing.JTextField();
        jButtonBooking = new javax.swing.JButton();
        jComboBoxTipeKamar = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaKeterangan = new javax.swing.JTextArea();
        jButtonKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(21, 62, 84));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BOOKING HOTEL");

        jPanel3.setBackground(new java.awt.Color(30, 89, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });

        jTextFieldNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNIKActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NIK");

        jTextFieldLamaMenginap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldLamaMenginap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLamaMenginapActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Harga");

        jTextFieldTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Uang Bayar");

        jTextFieldUangBayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldUangBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUangBayarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Uang Kembali");

        jTextFieldUangKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jButtonBooking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBooking.setText("Booking");
        jButtonBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookingActionPerformed(evt);
            }
        });

        jComboBoxTipeKamar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxTipeKamar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "pilih", "Single Room", "Double Room", "Suite Room", "Deluxe Room", " " }));
        jComboBoxTipeKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipeKamarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lama Menginap (Hari)");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pilih Tipe Kamar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUangKembali)
                    .addComponent(jTextFieldUangBayar)
                    .addComponent(jTextFieldTotalHarga)
                    .addComponent(jTextFieldLamaMenginap)
                    .addComponent(jTextFieldNIK)
                    .addComponent(jTextFieldNama)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxTipeKamar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLamaMenginap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUangKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButtonBooking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextAreaKeterangan.setColumns(20);
        jTextAreaKeterangan.setRows(5);
        jScrollPane1.setViewportView(jTextAreaKeterangan);

        jButtonKeluar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(30, 89, 120));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(227, 205, 118));
        jLabel14.setText("Tipe Kamar");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Single Room");

        jList5.setBackground(new java.awt.Color(0, 153, 153));
        jList5.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jList5.setForeground(new java.awt.Color(255, 255, 255));
        jList5.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "- Kamar Luas", "- Bed King Size", "- Bath tub", "- AC", "- TV+Netflix", "- Minibar" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList5);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Suite Room");

        jList4.setBackground(new java.awt.Color(0, 153, 153));
        jList4.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jList4.setForeground(new java.awt.Color(255, 255, 255));
        jList4.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "- Ruang tamu", "- Bed King Size", "- Bath Tub", "- AC", "- 2 TV+Netflix", "- Sarapan", "- CS 24 jam" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList4);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Double Room");

        jList2.setBackground(new java.awt.Color(0, 153, 153));
        jList2.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jList2.setForeground(new java.awt.Color(255, 255, 255));
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "- 1 kamar tidur", "- Bath tub", "- AC", "- TV", "- Wi-Fi" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jList3.setBackground(new java.awt.Color(0, 153, 153));
        jList3.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jList3.setForeground(new java.awt.Color(255, 255, 255));
        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "- 1 double bed", "- KamarMandi", "- AC", "- TV", "- Wi-Fi " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList3);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Deluxe Room");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel12)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonKeluar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jButtonKeluar))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        new Login().setVisible(true); // Kembali ke Login
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    private void jButtonBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookingActionPerformed
        saveBooking();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBookingActionPerformed

    private void jComboBoxTipeKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipeKamarActionPerformed
        updateKeteranganAndTotal();
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipeKamarActionPerformed

    private void jTextFieldNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNIKActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jTextFieldLamaMenginapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLamaMenginapActionPerformed
        updateKeteranganAndTotal();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLamaMenginapActionPerformed

    private void jTextFieldUangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUangBayarActionPerformed
        updateUangKembali();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUangBayarActionPerformed

   // --- Logic Methods ---
    private void updateKeteranganAndTotal() {
        String selectedRoomType = (String) jComboBoxTipeKamar.getSelectedItem();
        int lamaMenginap = 0;
        try {
            lamaMenginap = Integer.parseInt(jTextFieldLamaMenginap.getText());
        } catch (NumberFormatException ex) {
            jTextFieldTotalHarga.setText("Input Tidak Valid");
            jTextAreaKeterangan.setText("Lama Menginap harus berupa angka.");
            return;
        }

        double pricePerNight = 0;
        String roomDetails = "";

        switch (selectedRoomType) {
            case "Single Room":
                pricePerNight = SINGLE_ROOM_PRICE;
                roomDetails = "Single Room: - 1 kamar tidur\n- Bath tub\n- AC\n- TV\n- Wi-Fi";
                break;
            case "Double Room":
                pricePerNight = DOUBLE_ROOM_PRICE;
                roomDetails = "Double Room: - 1 double bed\n- Kamar Mandi\n- AC\n- TV\n- Wi-Fi";
                break;
            case "Suite Room":
                pricePerNight = SUITE_ROOM_PRICE;
                roomDetails = "Suite Room: - Kamar Luas\n- Bed King Size\n- Bath tub\n- AC\n- TV+Netflix\n- Minibar";
                break;
            case "Deluxe Room":
                pricePerNight = DELUXE_ROOM_PRICE;
                roomDetails = "Deluxe Room: - Ruang tamu\n- Bed King Size\n- Bath tub\n- AC\n- 2 TV+Netflix\n- Sarapan\n- CS 24 jam";
                break;
            default:
                pricePerNight = 0;
                roomDetails = "Silakan pilih tipe kamar.";
                break;
        }

        double totalHarga = pricePerNight * lamaMenginap;
        jTextFieldTotalHarga.setText(String.valueOf(totalHarga));
        jTextAreaKeterangan.setText("--- Detail Booking Anda ---\n" +
                                   "Tipe Kamar: " + selectedRoomType + "\n" +
                                   "Lama Menginap: " + lamaMenginap + " hari\n" +
                                   "Harga per Malam: Rp " + pricePerNight + "\n" +
                                   "Total Harga: Rp " + totalHarga + "\n\n" +
                                   "--- Fasilitas Kamar ---\n" +
                                   roomDetails);
        updateUangKembali();
    }

private void updateUangKembali() {
    try {
        // Hapus semua spasi di awal/akhir string dan pastikan format numerik yang benar
        String totalHargaText = jTextFieldTotalHarga.getText().trim();
        String uangBayarText = jTextFieldUangBayar.getText().trim();

        // Cek apakah ada teks yang bukan angka atau kosong
        if (totalHargaText.isEmpty() || !totalHargaText.matches("-?\\d+(\\.\\d+)?")) {
            jTextFieldUangKembali.setText("Total Harga Invalid");
            return;
        }
        if (uangBayarText.isEmpty() || !uangBayarText.matches("-?\\d+(\\.\\d+)?")) {
            jTextFieldUangKembali.setText("Uang Bayar Invalid");
            return;
        }

        double totalHarga = Double.parseDouble(totalHargaText);
        double uangBayar = Double.parseDouble(uangBayarText);

        double uangKembali = uangBayar - totalHarga;

        jTextFieldUangKembali.setText(String.format("%.2f", uangKembali)); // Format ke 2 angka di belakang koma

        // Perbarui jTextAreaKeterangan dengan informasi pembayaran
        String currentKeterangan = jTextAreaKeterangan.getText();
        String paymentInfo = "\n\n--- Informasi Pembayaran ---\nUang Bayar: Rp " + String.format("%.2f", uangBayar) + "\nUang Kembali: Rp " + String.format("%.2f", uangKembali);

        // Jika informasi pembayaran sudah ada, perbarui. Jika belum, tambahkan.
        if (currentKeterangan.contains("--- Informasi Pembayaran ---")) {
            // Jika sudah ada, cari bagian informasi pembayaran dan gantikan
            int startIndex = currentKeterangan.indexOf("--- Informasi Pembayaran ---");
            jTextAreaKeterangan.setText(currentKeterangan.substring(0, startIndex) + paymentInfo);
        } else {
            // Jika belum ada, tambahkan di akhir
            jTextAreaKeterangan.setText(currentKeterangan + paymentInfo);
        }

    } catch (NumberFormatException ex) {
        // Ini akan menangani kasus di mana parseDouble gagal meskipun regex sudah lewat
        // (misalnya jika string terlalu panjang untuk Double, meskipun jarang terjadi)
        jTextFieldUangKembali.setText("Format Angka Salah");
        jTextAreaKeterangan.setText(jTextAreaKeterangan.getText() + "\n\nError: Format angka untuk pembayaran tidak valid.");
    } catch (Exception ex) {
        // Tangani error umum lainnya
        jTextFieldUangKembali.setText("Error");
        jTextAreaKeterangan.setText(jTextAreaKeterangan.getText() + "\n\nTerjadi kesalahan: " + ex.getMessage());
    }
}

    private void saveBooking() {
        String nama = jTextFieldNama.getText();
        String nik = jTextFieldNIK.getText();
        String tipeKamar = (String) jComboBoxTipeKamar.getSelectedItem();
        int lamaMenginap;
        double totalBayar;

        if (nama.isEmpty() || nik.isEmpty() || tipeKamar == null || tipeKamar.equals("pilih") || jTextFieldLamaMenginap.getText().isEmpty() || jTextFieldTotalHarga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mohon lengkapi semua data!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            lamaMenginap = Integer.parseInt(jTextFieldLamaMenginap.getText());
            totalBayar = Double.parseDouble(jTextFieldTotalHarga.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Lama Menginap dan Total Harga harus angka!", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Connection conn = Koneksi.configDB();
            String sql = "INSERT INTO customers (nama, nik, tipe_kamar, lama_menginap, total_bayar, tanggal_booking) VALUES (?, ?, ?, ?, ?, NOW())";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, nik);
            pst.setString(3, tipeKamar);
            pst.setInt(4, lamaMenginap);
            pst.setDouble(5, totalBayar);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Booking Anda Berhasil! Terima kasih.");
            clearFields(); // Bersihkan field setelah simpan
            jTextAreaKeterangan.setText("Booking berhasil! Silakan mengisi form baru untuk booking lainnya."); // Tampilkan pesan konfirmasi di keterangan
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saat menyimpan booking: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearFields() {
        jTextFieldNama.setText("");
        jTextFieldNIK.setText("");
        if (jComboBoxTipeKamar != null) {
            jComboBoxTipeKamar.setSelectedIndex(0); // Setel ke item pertama (biasanya "pilih")
        }
        jTextFieldLamaMenginap.setText("");
        jTextFieldTotalHarga.setText("");
        jTextFieldUangBayar.setText("");
        jTextFieldUangKembali.setText("");
        jTextAreaKeterangan.setText("Pilih tipe kamar dan masukkan lama menginap untuk melihat detail dan total harga.");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBooking;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JComboBox jComboBoxTipeKamar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextAreaKeterangan;
    private javax.swing.JTextField jTextFieldLamaMenginap;
    private javax.swing.JTextField jTextFieldNIK;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField jTextFieldTotalHarga;
    private javax.swing.JTextField jTextFieldUangBayar;
    private javax.swing.JTextField jTextFieldUangKembali;
    // End of variables declaration//GEN-END:variables
}
